"""add search session tables

Revision ID: c487ba733353
Revises: fd6a9d199f32
Create Date: 2025-08-29 14:43:58.612451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c487ba733353'
down_revision: Union[str, Sequence[str], None] = 'fd6a9d199f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_session_cars', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('search_session_cars', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('search_session_cars_car_id_fkey'), 'search_session_cars', type_='foreignkey')
    op.create_foreign_key(None, 'search_session_cars', 'car_cache', ['car_id'], ['id'])
    op.add_column('search_sessions', sa.Column('params_json', sa.JSON(), nullable=True))
    op.alter_column('search_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('search_sessions_user_id_fkey'), 'search_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'search_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('search_sessions', 'used_credits')
    op.drop_column('search_sessions', 'filters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_sessions', sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('search_sessions', sa.Column('used_credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'search_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('search_sessions_user_id_fkey'), 'search_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('search_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('search_sessions', 'params_json')
    op.drop_constraint(None, 'search_session_cars', type_='foreignkey')
    op.create_foreign_key(op.f('search_session_cars_car_id_fkey'), 'search_session_cars', 'car_cache', ['car_id'], ['id'], ondelete='CASCADE')
    op.alter_column('search_session_cars', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('search_session_cars', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
